import os
import sys
from pathlib import Path

# Ensure project root is always in sys.path
PROJECT_ROOT = Path(__file__).resolve().parent.parent
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

import logging
from typing import Optional
from fastapi import FastAPI, HTTPException, status
from fastapi.exceptions import RequestValidationError
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import JSONResponse
from pydantic import BaseModel, Field
from starlette.exceptions import HTTPException as StarletteHTTPException

from backend.config import APP_NAME, APP_VERSION
from backend.ai_service import check_ollama_status, generate_response
from agents.langchain_agent import run_customer_agent
from graph.business_graph import business_graph

logger = logging.getLogger("dci.backend")
if not logger.handlers:
    handler = logging.StreamHandler()
    formatter = logging.Formatter("[%(asctime)s] [%(levelname)s] [DCI-FASTAPI] %(message)s", "%Y-%m-%d %H:%M:%S")
    handler.setFormatter(formatter)
    logger.addHandler(handler)
    logger.setLevel(logging.INFO)

app = FastAPI(
    title=APP_NAME,
    version=APP_VERSION,
    description="DCI AI Business Assistant - FastAPI Gateway powering Agentic Workflows with LangGraph, Ollama, MCP, and RAG."
)

# Exception handlers ensuring no stack traces or internal details are exposed
@app.exception_handler(RequestValidationError)
async def validation_exception_handler(request, exc: RequestValidationError):
    logger.warning("Request validation error: %s", str(exc))
    return JSONResponse(
        status_code=status.HTTP_400_BAD_REQUEST,
        content={"detail": "Invalid request payload. Ensure 'message' is provided and valid."},
    )

@app.exception_handler(StarletteHTTPException)
async def http_exception_handler(request, exc: StarletteHTTPException):
    return JSONResponse(
        status_code=exc.status_code,
        content={"detail": exc.detail},
    )

@app.exception_handler(Exception)
async def generic_exception_handler(request, exc: Exception):
    logger.error("Unhandled server exception: %s", type(exc).__name__)
    return JSONResponse(
        status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
        content={"detail": "A server error occurred. Please try again later."},
    )

# CORS configuration
ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "http://localhost:5173",
    "http://127.0.0.1:5173",
    "http://localhost:8000",
    "http://127.0.0.1:8000",
]

app.add_middleware(
    CORSMiddleware,
    allow_origins=ALLOWED_ORIGINS,
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

MAX_MESSAGE_LENGTH = 10000


class ChatRequest(BaseModel):
    message: str = Field(..., min_length=1, max_length=MAX_MESSAGE_LENGTH, description="User message or business request")
    context: str = Field(default="", description="Optional additional context")


class AssistantRequest(BaseModel):
    message: str = Field(
        ...,
        min_length=1,
        max_length=MAX_MESSAGE_LENGTH,
        description="Natural language business request or query for the assistant."
    )


class AssistantResponse(BaseModel):
    message: str = Field(..., description="The original user query processed by the assistant.")
    response: str = Field(..., description="The final business response generated by the agentic workflow.")
    decision: str = Field(..., description="Business decision: CREATE_TICKET, MORE_INFORMATION_REQUIRED, or NO_ACTION.")
    ticket: Optional[str] = Field(default=None, description="Support ticket details if created, otherwise omitted.")


@app.get("/")
async def root():
    return {
        "message": "DCI AI Business Assistant is running"
    }


@app.get(
    "/health",
    summary="Health Check",
    description="Verifies that the FastAPI backend is operational and checks local Ollama reachability."
)
async def health():
    """Health check reporting backend operational status and Ollama availability."""
    ollama_status = await check_ollama_status()
    return {
        "status": "healthy",
        "ollama": ollama_status
    }


@app.post("/chat")
async def chat(request: ChatRequest):
    if not request.message or not request.message.strip():
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="Message cannot be empty."
        )
    try:
        response = await generate_response(
            message=request.message,
            context=request.context
        )
        return {
            "message": request.message,
            "response": response
        }
    except Exception:
        return {
            "message": request.message,
            "response": "An error occurred while processing the chat request. Please try again."
        }


@app.post("/agent")
async def agent_chat(request: ChatRequest):
    if not request.message or not request.message.strip():
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="Message cannot be empty."
        )
    try:
        response = await run_customer_agent(
            request.message
        )
        return {
            "message": request.message,
            "response": response
        }
    except Exception:
        return {
            "message": request.message,
            "response": "An error occurred while executing the customer agent."
        }


@app.post("/workflow")
async def workflow_chat(request: ChatRequest):
    """
    Complete Agentic AI Business Support Workflow endpoint:
    Understands request, plans actions, retrieves info via MCP/RAG,
    analyzes via configured provider (Gemini/Ollama), generates business decision, and executes MCP actions.
    """
    if not request.message or not request.message.strip():
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="Message cannot be empty."
        )

    try:
        result = await business_graph.ainvoke({
            "question": request.message.strip(),
            "category": "",
            "customer_name": "",
            "customer_names": [],
            "required_actions": [],
            "customer_data": "",
            "complaint_data": "",
            "policy_context": "",
            "decision": "",
            "ticket_result": "",
            "response": "",
        })

        return {
            "message": request.message,
            "response": result.get("response", ""),
            "decision": result.get("decision", ""),
            "ticket": result.get("ticket_result", ""),
            "category": result.get("category", ""),
            "customer_data": result.get("customer_data", ""),
            "complaint_data": result.get("complaint_data", ""),
            "policy_context": result.get("policy_context", ""),
        }
    except Exception:
        return {
            "message": request.message,
            "response": "An error occurred while executing the business workflow. Please check your configuration and try again.",
            "decision": "MORE_INFORMATION_REQUIRED",
            "ticket": "",
            "category": "error",
            "customer_data": "",
            "complaint_data": "",
            "policy_context": "",
        }


@app.post(
    "/api/assistant",
    response_model=AssistantResponse,
    response_model_exclude_none=True,
    summary="Agentic AI Business Assistant Gateway",
    description="Processes natural-language business requests through LangGraph, MCP tools, ChromaDB RAG, and Ollama reasoning."
)
async def assistant_endpoint(request: AssistantRequest):
    """
    Dedicated Business Assistant Endpoint (STEP 10.4):
    Routes through LangGraph with Ollama, MCP tools, and RAG policy context.
    Returns clean response, business decision, and ticket result without exposing internal state.
    """
    cleaned_message = request.message.strip()
    if not cleaned_message:
        logger.warning("Assistant request rejected: empty message")
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="Message cannot be empty."
        )

    if len(cleaned_message) > MAX_MESSAGE_LENGTH:
        logger.warning("Assistant request rejected: message length %d exceeds %d", len(cleaned_message), MAX_MESSAGE_LENGTH)
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail=f"Message exceeds maximum allowed length of {MAX_MESSAGE_LENGTH} characters."
        )

    logger.info("Assistant request received (length: %d chars)", len(cleaned_message))
    logger.info("Executing LangGraph agentic workflow...")

    try:
        result = await business_graph.ainvoke({
            "question": cleaned_message,
            "category": "",
            "customer_name": "",
            "customer_names": [],
            "required_actions": [],
            "customer_data": "",
            "complaint_data": "",
            "policy_context": "",
            "decision": "",
            "ticket_result": "",
            "response": "",
        })

        decision = result.get("decision", "NO_ACTION")
        if decision not in ("CREATE_TICKET", "MORE_INFORMATION_REQUIRED", "NO_ACTION"):
            logger.warning("Invalid decision '%s' returned. Defaulting to safe fallback.", decision)
            decision = "MORE_INFORMATION_REQUIRED"

        ticket_res = result.get("ticket_result", "").strip() or None
        if ticket_res:
            logger.info("Ticket generated successfully via MCP: %s", ticket_res[:40])

        logger.info("LangGraph workflow completed. Decision: %s", decision)

        return AssistantResponse(
            message=cleaned_message,
            response=result.get("response", ""),
            decision=decision,
            ticket=ticket_res
        )
    except Exception as e:
        logger.error("Error during LangGraph assistant execution: %s", type(e).__name__)
        # Never expose stack traces, keys, or internal paths
        return AssistantResponse(
            message=cleaned_message,
            response="A system error occurred while processing your request. Please ensure the backend and AI services are running.",
            decision="MORE_INFORMATION_REQUIRED",
            ticket=None
        )


if __name__ == "__main__":
    import uvicorn
    uvicorn.run("backend.main:app", host="127.0.0.1", port=8000, reload=True)